config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :settings do

    end
    resources :qoutes do
      collection do
          get :random
      end
    end
    resources :tools

  end


  mount Commontator::Engine => '/commontator', as: :commontator

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


    get 'p/about' => 'pages#about', as: :about

    get 'p/contact' => 'pages#contact', as: :contact

    get 'p/blog' => 'pages#blog', as: :blog

    get 'p/feature' => 'pages#feature', as: :feature_artists

    # namespace :admin do
    #   get '/settings/:id/random_qoutes' => "settings#random_quotes", as: :get_random_qoutes
    # end
    constraints(subdomain: /www/) do
        root to: 'home#feeds'
    end

    constraints(subdomain: /.+/) do
        #root to: 'home#index'
        # professional pages
        match '/' => 'professional_pages#index', via: [:get], as: :professional_page
        match '/portfolio' => 'professional_pages#portfolio', via: [:get], as: :professional_page_portfolio
        match '/contact' => 'professional_pages#contact', via: [:get], as: :professional_page_contact
        match '/shop' => 'professional_pages#shop', via: [:get], as: :professional_page_shop
        match '/about' => 'professional_pages#pro', via: [:get], as: :professional_page_about
        # community pages

        match '/profile' => 'community_pages#com', via: [:get], as: :community_page
    end

    root to: 'home#feeds', as: :unauthenticated_root

    resources :categories

    devise_for :users

    authenticated :user do
        root to: 'photos#index', as: :authenticated_root
    end

    authenticate :user do

        resources :photos, only: [:new, :create, :edit, :update, :destroy] do
           collection do
             get "/:user_id/take_three" => "photos#take_three", as: :take_three

           end
           member do
               patch :view
               get :comments
               put "like", to: "photos#upvote"
               put "dislike", to: "photos#downvote"
           end
        end

        match 'users/:id/profile' => 'users#edit', as: 'user_profile', via: [:get]

        resources :users do
            member do
                get :portfolio
                get :photos
            end
            resources :follows, :only => [:create, :destroy]
        end

        match 'modals/:moda_type' => 'modals#show', as: :modal, via: [:get]
    end

    resources :photos, only: [:index, :show]



    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

 #, only: [ :dashboard ]
 before_action :set_user
 before_action :set_session

  def index
    @photos = Photo.take(4)
  end

  def feeds
    if @user
      @photos = @user.photos.order(created_at: :desc).page(params[:page])
    else
      @photos = Photo.all.order(created_at: :desc).page(params[:page])
    end
      @ig_photos=IgPhoto.instagram_photos
  end

  def get_random_qoutes
      @admin = Admin.find(params[:id])
      @qoutes = @admin.setting.qoutes_random
  end

  def dashboard

  end

  def set_user
   if !request.subdomain.to_s.blank?
     subdomain=request.subdomain.to_s.gsub("www.", "")
     logger.info "subdomain : #{subdomain}"
     @user=User.friendly.find(subdomain) if request.subdomain != "www"
   end
 end
   def set_session
     session[:page_type] = 0 # community_page
   end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_carousel.html.erb
<div id="carousel-qoutes" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <%@setting.qoutes_random.each_with_index  do |qoute,index|%>
            <li data-target="#carousel-qoutes" data-slide-to="<%=index%>" class="<%='active' if index == 0 %>"></li>
    <%end%>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox"  data-render="home qoute">
    <%#@setting.qoutes_random.each_with_index do |qoute,index|%>
    <%=render partial: "home/qoute", collection: @setting.qoutes_random, as: :qoute %>

    <%#end%>
  </div>
  <a class="left carousel-control" href="#carousel-qoutes" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-qoutes" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<%=javascript_tag do %>
$('#carousel-qoutes').carousel(
  {
   interval: 5000,
   pause: false }
   );
<%end%>

app/views/home/_carousel_photos.html.erb
<div id="carousel-photos" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouse-photos" data-slide-to="0" class="active"></li>
    <li data-target="#carouse-photos" data-slide-to="1"></li>
    <li data-target="#carouse-photos" data-slide-to="2"></li>
    <li data-target="#carouse-photos" data-slide-to="3"></li>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <%@photos.where(on_slide: true).each_with_index do |photo,index|%>
      <div class="item <%='active' if index == 0 %>">
        <!-- <img src="img_chania.jpg" alt="Chania"> -->
        <%=image_tag photo.image.url, width: "100%;"%>
      </div>
    <%end%>
  </div>
  <a class="left carousel-control" href="#carouse-photos" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carouse-photos" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/home/_qoute.html.erb
<div class="item <%='active' if qoute_counter == 0 %>">
  <center>
    <blockquote>
      <h3><%=qoute.description%></h3>
      <footer><%=qoute.author%></footer>
    </blockquote>
  </center>
</div>

app/views/home/feeds.html.erb
<div class="row">
  <div class="col-md-12">
      <ul class="list-inline list-unstyled">
      <%@ig_photos.each do |item|%>
      <%#=item.inspect%>
          <li><%=link_to feature_artists_url(ig_id: item["id"]) do%><%=image_tag item["images"]["thumbnail"]["url"]%><%end%></li>
      <%end%>
    </ul>
        <%#=@setting.inspect%>
  </div>
</div>
<%=render partial: "home/carousel"%>
<%#=session[:setting].qoutes%>
<%=render partial: "photos/gallery" if @photos%>
<%#=render partial: "photos/quotecarousel"%>

app/views/home/index.html.erb
<%#=render partial: "photos/carousel"%>
<%#=render partial: "photos/gallery"%>
<%#=render partial: "photos/quotecarousel"%>
<div class="row">
    <div class="col-md-12">
        <%=render partial: "home/carousel"%>
    </div>
    <div class="col-md-4">
        <h3 class="text-center"> Portfolio </h3>
        <%=image_tag "http://placehold.it/350x250"%>
    </div>
    <div class="col-md-4">
        <h3 class="text-center"> Shop Picture </h3>
        <%=image_tag "http://placehold.it/350x250"%>
    </div>
    <div class="col-md-4">
        <h3 class="text-center"> Free Box </h3>
        <%=image_tag "http://placehold.it/350x250"%>
    </div>
</div>