config/routes.rb
Rails.application.routes.draw do

  namespace :admin do

    resources :settings do

    end
    resources :qoutes do
      collection do
          get :random
      end
    end
    resources :tools

  end


  mount Commontator::Engine => '/commontator', as: :commontator

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


    get 'p/about' => 'pages#about', as: :about

    get 'p/contact' => 'pages#contact', as: :contact

    get 'p/blog' => 'pages#blog', as: :blog

    get 'p/feature' => 'pages#feature', as: :feature_artists

    # namespace :admin do
    #   get '/settings/:id/random_qoutes' => "settings#random_quotes", as: :get_random_qoutes
    # end
    constraints(subdomain: /www/) do
        root to: 'home#feeds'
    end

    constraints(subdomain: /.+/) do
        #root to: 'home#index'
        # professional pages
        match '/' => 'professional_pages#index', via: [:get], as: :professional_page
        match '/portfolio' => 'professional_pages#portfolio', via: [:get], as: :professional_page_portfolio
        match '/contact' => 'professional_pages#contact', via: [:get], as: :professional_page_contact
        match '/shop' => 'professional_pages#shop', via: [:get], as: :professional_page_shop
        match '/about' => 'professional_pages#pro', via: [:get], as: :professional_page_about
        # community pages

        match '/profile' => 'community_pages#com', via: [:get], as: :community_page
    end

    root to: 'home#feeds', as: :unauthenticated_root

    resources :categories

    devise_for :users

    authenticated :user do
        root to: 'photos#index', as: :authenticated_root
    end

    authenticate :user do

        resources :photos, only: [:new, :create, :edit, :update, :destroy] do
           collection do
             get "/:user_id/take_three" => "photos#take_three", as: :take_three

           end
           member do
               patch :view
               get :comments
               put "like", to: "photos#upvote"
               put "dislike", to: "photos#downvote"
           end
        end

        match 'users/:id/profile' => 'users#edit', as: 'user_profile', via: [:get]

        resources :users do
            member do
                get :portfolio
                get :photos
            end
            resources :follows, :only => [:create, :destroy]
        end

        match 'modals/:moda_type' => 'modals#show', as: :modal, via: [:get]
    end

    resources :photos, only: [:index, :show]



    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin/setting.rb
class Admin::Setting < ApplicationRecord

  has_many :qoutes
  has_attached_file :logo,
                    styles: {
                        medium: '300x300>',
                        thumb: '100x100>'
                    },
                    storage: :s3,
                    s3_credentials: proc { |a| a.instance.s3_credentials },
                    s3_protocol: :https,
                    default_url: 'https://i.imgur.com/pqpsxlQ.png',
                    url: '/users/:attachment/:id/:style/:filename'
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

  def s3_credentials
      {
          bucket: ENV.fetch('S3_BUCKET_NAME'),
          access_key_id: ENV.fetch('AWS_ACCESS_KEY_ID').to_s,
          secret_access_key: ENV.fetch('AWS_SECRET_ACCESS_KEY').to_s,
          s3_region: ENV.fetch('AWS_REGION').to_s,
          endpoint: ENV.fetch('AWS_S3_ENDPOINT').to_s
      }
  end


  def qoutes_random
      qoutes.limit(10).order("RANDOM()")
  end

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < ApplicationController
  before_action :set_admin_setting, only: [:show, :edit, :update, :destroy, :random_qoutes]

  # GET /admin/settings
  # GET /admin/settings.json
  def index
    @admin_settings = Admin::Setting.all
  end

  # GET /admin/settings/1
  # GET /admin/settings/1.json
  def show
  end

  # GET /admin/settings/new
  def new
    @admin_setting = Admin::Setting.new
  end

  # GET /admin/settings/1/edit
  def edit
  end

  # POST /admin/settings
  # POST /admin/settings.json
  def create
    @admin_setting = Admin::Setting.new(admin_setting_params)

    respond_to do |format|
      if @admin_setting.save
        format.html { redirect_to @admin_setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @admin_setting }
      else
        format.html { render :new }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/settings/1
  # PATCH/PUT /admin/settings/1.json
  def update
    respond_to do |format|
      if @admin_setting.update(admin_setting_params)
        format.html { redirect_to @admin_setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_setting }
      else
        format.html { render :edit }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/settings/1
  # DELETE /admin/settings/1.json
  def destroy
    @admin_setting.destroy
    respond_to do |format|
      format.html { redirect_to admin_settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_setting
      @admin_setting = Admin::Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_setting_params
      params.require(:admin_setting).permit(:app_name)
    end
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/_form.html.erb
<%= form_for(admin_setting) do |f| %>
  <% if admin_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_setting.errors.count, "error") %> prohibited this admin_setting from being saved:</h2>

      <ul>
      <% admin_setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :app_name %>
    <%= f.text_field :app_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/settings/edit.html.erb
<h1>Editing Admin Setting</h1>

<%= render 'form', admin_setting: @admin_setting %>

<%= link_to 'Show', @admin_setting %> |
<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Settings</h1>

<table>
  <thead>
    <tr>
      <th>App name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_settings.each do |admin_setting| %>
      <tr>
        <td><%= admin_setting.app_name %></td>
        <td><%= link_to 'Show', admin_setting %></td>
        <td><%= link_to 'Edit', edit_admin_setting_path(admin_setting) %></td>
        <td><%= link_to 'Destroy', admin_setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Setting', new_admin_setting_path %>

app/views/admin/settings/new.html.erb
<h1>New Admin Setting</h1>

<%= render 'form', admin_setting: @admin_setting %>

<%= link_to 'Back', admin_settings_path %>

app/views/admin/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App name:</strong>
  <%= @admin_setting.app_name %>
</p>

<%= link_to 'Edit', edit_admin_setting_path(@admin_setting) %> |
<%= link_to 'Back', admin_settings_path %>